import { Inter } from "next/font/google";
import "./globals.css";
import { ThirdwebProvider } from "thirdweb/react";
import { ThirdwebProviderV4 } from "@/components/ThirdwebProviderV4";
import { ThirdwebProviderV5 } from "@/components/ThirwebProviderV5";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ThirdwebProviderV4 clientId="545a4505872f4f3f18f1bade9dca58da">
					<ThirdwebProviderV5>{children}</ThirdwebProviderV5>
				</ThirdwebProviderV4>
			</body>
		</html>
	);
}
